# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ gfortran libatlas-base-dev && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the requirements and project files
COPY setup.py ./
COPY bp_percentile/ ./bp_percentile/

# Install the package
RUN pip install --no-cache-dir .

# Expose any port if required (not needed here)

# Run the MCP server
CMD [ "python", "-m", "bp_percentile" ]
